---
- name: Get kernel version
  command: uname --kernel-release
  register: kernelrelease
  changed_when: False

- name: install required packages
  apt:
    name: ['gpsd', 'gpsd-clients', 'chrony', 'pps-tools', 'python3-pip', 'linux-headers-{{ kernelrelease.stdout.strip() }}']
    state: present

- name: configure chrony and gpsd
  template:
    src: '{{ gps_path }}/{{ item }}.conf'
    dest: '/etc/shepherd/'
    mode: 0644
  with_items:
   - chrony
   - gpsd
  tags: conf

- name: Disable factory enabled capes
  lineinfile:
    dest: '{{ uEnv }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
   - { line: 'disable_uboot_overlay_video=1', regexp: '#?disable_uboot_overlay_video=1' }
   - { line: 'disable_uboot_overlay_adc=1', regexp: '#?disable_uboot_overlay_adc=1' }
   - { line: 'disable_uboot_overlay_audio=1', regexp: '#?disable_uboot_overlay_audio=1' }
   - { line: 'disable_uboot_overlay_wireless=1', regexp: '#?disable_uboot_overlay_wireless=1' }
   - { line: '#enable_uboot_cape_universal=1', regexp: '#?enable_uboot_cape_universal=1' }

- name: Set enabled capes
  lineinfile:
    dest: '{{ uEnv }}'
    regexp: '#?uboot_overlay_addr1=\/lib\/firmware\/(<file8>|BB-GPS-00A0).dtbo'
    line: 'uboot_overlay_addr1=/lib/firmware/BB-GPS-00A0.dtbo'
    state: present

- name: Copy pps-gmtimer code
  synchronize:
    src: '{{ pps_gmtimer_path }}'
    dest: /opt/pps-gmtimer
  tags: pps

- name: Build and install pps-gmtimer module
  make:
    chdir: /opt/pps-gmtimer
    target: install
  tags: pps

- name: Copy pps-gmtimer code
  synchronize:
    src: '{{ gps_path }}'
    dest: /opt/gps

- name: Build and install device tree overlay
  make:
    chdir: "/opt/gps"
    target: install
  tags:
    - device-tree

- name: make system find kernel-modul
  command: depmod -ae

- name: Install ubx-serial
  pip:
    name: ubxserial
    state: present
    executable: pip3

- name: Copy ublox config file
  copy:
    src: '{{ gps_path }}/ublox_config.ubx'
    dest: /etc/shepherd/

- include_tasks: systemd.yml
  tags:
   - conf
   - systemd

- name: restart device
  shell: sleep 2 && shutdown -r now "Ansible restart"
  async: 1
  poll: 0
  ignore_errors: true


- name: waiting to come back
  wait_for_connection:
    delay: 15
    timeout: 300
  become: no
