---
- name: Prepare paths for service override
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
    recurse: yes
  with_items:
    - gpsd
    - chrony

- name: Override service configs
  copy:
    src: "{{ gps_path }}/{{ item }}.override.conf"
    dest: "/etc/systemd/system/{{ item }}.service.d/"
  with_items:
    - chrony
    - gpsd

- name: Add config systemd service
  template:
    src: "{{ gps_path }}/debian/shepherd-gps.ublox-config.service"
    dest: "/etc/systemd/system/ublox-config.service"

- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  with_items:
    - gpsd.socket
    - gpsd.service
    - chrony.service
    - ublox-config.service
