MAX_GPIO_EVT_PER_BUFFER = 16384

MSG_DEP_ERROR = 0
MSG_DEP_BUF_FROM_HOST = 1
MSG_DEP_BUF_FROM_PRU = 2

MSG_DEP_ERR_INCMPLT = 3
MSG_DEP_ERR_INVLDCMD = 4
MSG_DEP_ERR_NOFREEBUF = 5

MSG_DEP_DBG_ADC = 0xF0
MSG_DEP_DBG_DAC = 0xF1
