---
- name: Add systemd unit
  copy:
    src: '{{ repo_dir.stdout }}/software/meta-package/debian/shepherd.{{ item }}.service'
    dest: '/etc/systemd/system/{{ item }}.service'
  with_items:
   - shepherd
   - shepherd-rpc
   - shepherd-launcher
  tags:
    - install
    - systemd

- name: Configure systemd services
  systemd:
    name: '{{ item.name }}'
    state: stopped
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
   - { name: shepherd, enabled: no}
   - { name: shepherd-rpc, enabled: no}
   - { name: shepherd-launcher, enabled: yes}
   - { name: systemd-timesyncd, enabled: no}
  tags:
    - conf
    - systemd
