---
- name: Install ptp package
  apt:
    update_cache: yes
    name: linuxptp
    state: present
  tags: ptp

- name: Create systemd overlay directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/systemd/system/phc2sys.service.d/
    - /etc/systemd/system/ptp4l.service.d/
  tags:
    - ptp
    - conf

- name: Deploy systemd overlay files
  copy:
    src: "{{ role_path }}/../../../software/ptp/{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
    mode: 0644
  with_items:
    - {
        src: "phc2sys_mands.conf",
        dest: "phc2sys.service.d/phc2sys_mands.conf",
      }
    - { src: "ptp_restart.conf", dest: "ptp4l.service.d/ptp_restart.conf" }
  tags:
    - ptp
    - conf

- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  with_items:
    - phc2sys.service
    - ptp4l.service
  tags:
    - ptp
    - conf
